blueprint:
  name: "Automatic lights based on motion and house mode"
  description: >
    Controls the light based on motion and house mode.
  domain: automation
  input:
    motion_sensor:
      name: Motion Sensor
      description: Choose the motion sensor to use.
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    light_entity:
      name: Light
      description: Choose the light to control.
      selector:
        entity:
          domain: light
    secondary_entity:
      name: Secondary Light or Switch (optional)
      description: Optional secondary light or switch to control.
      default: []
      selector:
        entity:
          multiple: false
          filter:
            - domain: light
            - domain: switch
    delay_turn_off:
      name: Delay to Turn Off
      description: Seconds to wait before turning off the light after motion stops.
      default: 300
      selector:
        number:
          min: 1
          max: 3600
          unit_of_measurement: seconds
    brightness_night:
      name: Brightness Level Night
      description: Brightness level when house mode is 'Natt'.
      default: 1
      selector:
        number:
          min: 1
          max: 100
    brightness_late:
      name: Brightness Level Late
      description: Brightness level for late hours.
      default: 30
      selector:
        number:
          min: 1
          max: 100
    brightness_default:
      name: Brightness Level Default
      description: Default brightness level.
      default: 70
      selector:
        number:
          min: 1
          max: 100

trigger:
  - platform: state
    entity_id: !input motion_sensor
    from: "off"
    to: "on"
  - platform: state
    entity_id: input_select.house_mode

condition: []

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input motion_sensor
            state: 'on'
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: input_select.house_mode
                    state: 'Natt'
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: !input light_entity
                    data:
                      brightness_pct: !input brightness_night
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ (states('!input secondary_entity') != 'unavailable') and (states('!input secondary_entity') != 'unknown') and (!is_state('!input secondary_entity', '')) }}"
                        sequence:
                          - choose:
                              - conditions:
                                  - condition: template
                                    value_template: "{{ '!input secondary_entity'.split('.')[0] == 'light' }}"
                                sequence:
                                  - service: light.turn_on
                                    target:
                                      entity_id: !input secondary_entity
                                    data:
                                      brightness_pct: !input brightness_night
                              - conditions:
                                  - condition: template
                                    value_template: "{{ '!input secondary_entity'.split('.')[0] == 'switch' }}"
                                sequence:
                                  - service: switch.turn_on
                                    target:
                                      entity_id: !input secondary_entity
              - conditions:
                  - condition: time
                    after: "19:00:00"
                    weekday:
                      - sun
                      - mon
                      - tue
                      - wed
                      - thu
                      - fri
                      - sat
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: !input light_entity
                    data:
                      brightness_pct: !input brightness_late
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ (states('!input secondary_entity') != 'unavailable') and (states('!input secondary_entity') != 'unknown') and (!is_state('!input secondary_entity', '')) }}"
                        sequence:
                          - choose:
                              - conditions:
                                  - condition: template
                                    value_template: "{{ '!input secondary_entity'.split('.')[0] == 'light' }}"
                                sequence:
                                  - service: light.turn_on
                                    target:
                                      entity_id: !input secondary_entity
                                    data:
                                      brightness_pct: !input brightness_late
                              - conditions:
                                  - condition: template
                                    value_template: "{{ '!input secondary_entity'.split('.')[0] == 'switch' }}"
                                sequence:
                                  - service: switch.turn_on
                                    target:
                                      entity_id: !input secondary_entity
              - conditions: []
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: !input light_entity
                    data:
                      brightness_pct: !input brightness_default
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ (states('!input secondary_entity') != 'unavailable') and (states('!input secondary_entity') != 'unknown') and (!is_state('!input secondary_entity', '')) }}"
                        sequence:
                          - choose:
                              - conditions:
                                  - condition: template
                                    value_template: "{{ '!input secondary_entity'.split('.')[0] == 'light' }}"
                                sequence:
                                  - service: light.turn_on
                                    target:
                                      entity_id: !input secondary_entity
                                    data:
                                      brightness_pct: !input brightness_default
                              - conditions:
                                  - condition: template
                                    value_template: "{{ '!input secondary_entity'.split('.')[0] == 'switch' }}"
                                sequence:
                                  - service: switch.turn_on
                                    target:
                                      entity_id: !input secondary_entity
          - wait_for_trigger:
              - platform: state
                entity_id: !input motion_sensor
                from: 'on'
                to: 'off'
          - delay: !input delay_turn_off
          - service: light.turn_off
            target:
              entity_id: !input light_entity
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ (states('!input secondary_entity') != 'unavailable') and (states('!input secondary_entity') != 'unknown') and (!is_state('!input secondary_entity', '')) }}"
                sequence:
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ '!input secondary_entity'.split('.')[0] == 'light' }}"
                        sequence:
                          - service: light.turn_off
                            target:
                              entity_id: !input secondary_entity
                      - conditions:
                          - condition: template
                            value_template: "{{ '!input secondary_entity'.split('.')[0] == 'switch' }}"
                        sequence:
                          - service: switch.turn_off
                            target:
                              entity_id: !input secondary_entity
    default:
      - service: light.turn_off
        target:
          entity_id: !input light_entity
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ (states('!input secondary_entity') != 'unavailable') and (states('!input secondary_entity') != 'unknown') and (!is_state('!input secondary_entity', '')) }}"
            sequence:
              - choose:
                  - conditions:
                      - condition: template
                        value_template: "{{ '!input secondary_entity'.split('.')[0] == 'light' }}"
                    sequence:
                      - service: light.turn_off
                        target:
                          entity_id: !input secondary_entity
                  - conditions:
                      - condition: template
                        value_template: "{{ '!input secondary_entity'.split('.')[0] == 'switch' }}"
                    sequence:
                      - service: switch.turn_off
                        target:
                          entity_id: !input secondary_entity

mode: restart
max_exceeded: silent